<a href="https://colab.research.google.com/github/pavan-elisetty/jovian-DL-notebooks/blob/main/california_house_prices_linreg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch


In [2]:
data=pd.read_csv('/content/sample_data/california_housing_train.csv',header=[0])
data.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [3]:
data=data.drop(labels=['longitude','latitude'],axis=1)
data.head()

housing_median_age  total_rooms  ...  median_income  median_house_value
0                15.0       5612.0  ...         1.4936             66900.0
1                19.0       7650.0  ...         1.8200             80100.0
2                17.0        720.0  ...         1.6509             85700.0
3                14.0       1501.0  ...         3.1917             73400.0
4                20.0       1454.0  ...         1.9250             65500.0

[5 rows x 7 columns]

In [4]:
x=data.drop('median_house_value',axis=1).values
x=x.astype('float32')
x

array([[1.5000e+01, 5.6120e+03, 1.2830e+03, 1.0150e+03, 4.7200e+02,
        1.4936e+00],
       [1.9000e+01, 7.6500e+03, 1.9010e+03, 1.1290e+03, 4.6300e+02,
        1.8200e+00],
       [1.7000e+01, 7.2000e+02, 1.7400e+02, 3.3300e+02, 1.1700e+02,
        1.6509e+00],
       ...,
       [1.7000e+01, 2.6770e+03, 5.3100e+02, 1.2440e+03, 4.5600e+02,
        3.0313e+00],
       [1.9000e+01, 2.6720e+03, 5.5200e+02, 1.2980e+03, 4.7800e+02,
        1.9797e+00],
       [5.2000e+01, 1.8200e+03, 3.0000e+02, 8.0600e+02, 2.7000e+02,
        3.0147e+00]], dtype=float32)

In [5]:
y=data['median_house_value'].values
y=y.astype('float32')
y

array([ 66900.,  80100.,  85700., ..., 103600.,  85800.,  94600.],
      dtype=float32)

In [6]:
inputs=torch.from_numpy(x)
targets=torch.from_numpy(y)
targets=targets.reshape(17000,1)
targets

tensor([[ 66900.],
        [ 80100.],
        [ 85700.],
        ...,
        [103600.],
        [ 85800.],
        [ 94600.]])

In [7]:
torch.manual_seed(3)
from torch.utils.data import DataLoader,TensorDataset
tensor_data=TensorDataset(inputs,targets)
batch_size=20
train_data=DataLoader(tensor_data,batch_size,shuffle=True)

In [8]:
for x,y in train_data:
  print(x)
  print(y)
  break

tensor([[4.0000e+00, 5.8000e+01, 2.9000e+01, 7.9000e+01, 2.9000e+01, 3.3750e+00],
        [5.2000e+01, 7.6900e+02, 2.0600e+02, 6.1200e+02, 1.8300e+02, 2.5700e+00],
        [2.9000e+01, 8.8900e+02, 1.6600e+02, 5.9700e+02, 1.6300e+02, 4.9609e+00],
        [5.0000e+00, 9.2690e+03, 1.6050e+03, 4.9160e+03, 1.5190e+03, 4.4367e+00],
        [2.7000e+01, 3.0440e+03, 5.6500e+02, 1.5830e+03, 5.1400e+02, 2.7989e+00],
        [2.3000e+01, 1.8580e+03, 5.5100e+02, 1.5060e+03, 4.9200e+02, 1.7446e+00],
        [2.8000e+01, 5.2740e+03, 9.9100e+02, 3.7270e+03, 9.6100e+02, 3.5700e+00],
        [3.8000e+01, 7.2700e+02, 1.7300e+02, 5.5900e+02, 1.7600e+02, 2.4653e+00],
        [1.9000e+01, 2.0120e+03, 7.3200e+02, 3.4830e+03, 7.3100e+02, 2.2234e+00],
        [3.3000e+01, 1.2930e+03, 2.7200e+02, 6.9400e+02, 2.2900e+02, 2.0221e+00],
        [5.2000e+01, 1.8440e+03, 3.9200e+02, 6.6700e+02, 3.5300e+02, 3.0033e+00],
        [2.1000e+01, 2.3700e+03, 5.4000e+02, 1.4880e+03, 5.5400e+02, 2.7361e+00],
        [7.0000e

In [9]:
import torch.nn as nn
model=nn.Linear(6,1)

In [10]:
print(model.weight)
print(model.bias)
print(*model.parameters())

Parameter containing:
tensor([[-0.1720, -0.2316,  0.2347,  0.2680, -0.3696,  0.2764]],
       requires_grad=True)
Parameter containing:
tensor([0.4035], requires_grad=True)
Parameter containing:
tensor([[-0.1720, -0.2316,  0.2347,  0.2680, -0.3696,  0.2764]],
       requires_grad=True) Parameter containing:
tensor([0.4035], requires_grad=True)


In [11]:
pred=model(inputs)
print(pred)

tensor([[ -902.9592],
        [-1196.6945],
        [  -81.9924],
        ...,
        [ -332.2466],
        [ -320.4539],
        [ -242.6244]], grad_fn=<AddmmBackward>)


In [14]:
#defining loss function
from torch.nn.functional import mse_loss
loss_fn=mse_loss
#test
loss=loss_fn(model(inputs),targets)

print(loss)

tensor(5.6564e+10, grad_fn=<MseLossBackward>)


In [15]:
inputs.shape[0]==targets.shape[0]

True

In [16]:
#defining optimizer
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [17]:
def fit(model,num_epochs,loss_fn,train_dl,opt):

  for epoch in range(num_epochs):

    for x,y in train_dl:

      pred=model(x)

      loss=loss_fn(x,y)

      loss.backward()

      opt.step()

      opt.zero_grad()
      if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

    

In [ ]:
num_epochs=100
fit(model,num_epochs,loss_fn,train_data,opt)