<a href="https://colab.research.google.com/github/pavan-elisetty/jovian-DL-notebooks/blob/main/linear_reg_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [2]:
#Train data
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
print(inputs.shape)

(5, 3)


In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
#weights and biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
w,b

(tensor([[-0.5254, -1.4857, -0.8407],
         [ 0.6506, -2.2724, -1.8995]], requires_grad=True),
 tensor([ 2.4743, -0.1917], requires_grad=True))

In [5]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [6]:
def model(input_values):
  return input_values@w.t() + b


In [7]:
pred=model(inputs)

In [8]:
#mse loss
def mse(predictions,targets):
  diff=predictions-targets
  return torch.sum(diff*diff)/diff.numel()


In [9]:
loss=mse(pred,targets)
print(loss)

tensor(109888.2656, grad_fn=<DivBackward0>)


In [10]:
loss.backward()

In [11]:
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[-0.5254, -1.4857, -0.8407],
        [ 0.6506, -2.2724, -1.8995]], requires_grad=True)
tensor([[-24213.3359, -27451.3633, -16672.9121],
        [-27613.8242, -32364.7031, -19541.9902]])
tensor([ 2.4743, -0.1917], requires_grad=True)
tensor([-290.9796, -335.1331])


In [12]:
with torch.no_grad():
  w -= w.grad*1e-5
  b -=b.grad*1e-5
  print(w)
  print(b)
  

tensor([[-0.2833, -1.2112, -0.6739],
        [ 0.9267, -1.9487, -1.7041]], requires_grad=True)
tensor([ 2.4772, -0.1883], requires_grad=True)


In [13]:
mse(pred,targets)

tensor(109888.2656, grad_fn=<DivBackward0>)

In [14]:
w.grad.zero_()
b.grad.zero_()
w.grad,b.grad

(tensor([[0., 0., 0.],
         [0., 0., 0.]]), tensor([0., 0.]))

In [15]:
# sequential implementation 
pred=model(inputs)
print(pred)
loss=mse(pred,targets)
print(loss)


tensor([[-128.3316, -136.3800],
        [-173.0185, -196.4087],
        [-223.5563, -279.5324],
        [-103.4347,  -52.5116],
        [-180.5194, -242.6106]], grad_fn=<AddBackward0>)
tensor(75196.7656, grad_fn=<DivBackward0>)


In [16]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-19746.2949, -22643.5879, -13707.8301],
        [-22420.3125, -26768.4785, -16092.0098]])
tensor([-237.9721, -273.4887])


In [17]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
    print(w)
    print(b)

tensor([[-0.0858, -0.9848, -0.5369],
        [ 1.1509, -1.6810, -1.5432]], requires_grad=True)
tensor([ 2.4796, -0.1856], requires_grad=True)


In [18]:
print(w)
print(b)

tensor([[-0.0858, -0.9848, -0.5369],
        [ 1.1509, -1.6810, -1.5432]], requires_grad=True)
tensor([ 2.4796, -0.1856], requires_grad=True)


In [19]:
# Calculate loss
preds = model(inputs) #to see a change in loss we need to go with new predictions for the model after the gradient updation
loss = mse(preds, targets)
print(loss)

tensor(51804.7109, grad_fn=<DivBackward0>)


In [20]:
for _ in range(100): #training for 100 epochs
    preds=model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
      w -= w.grad*1e-5
      b -= b.grad*1e-5
      w.grad.zero_()
      b.grad.zero_()
print(loss)


tensor(1088.5950, grad_fn=<DivBackward0>)


In [21]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1076.1155, grad_fn=<DivBackward0>)


In [22]:
# using torch high level apis
import torch.nn as nn
import numpy as np

In [23]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [24]:
from torch.utils.data import TensorDataset 

In [25]:
train_data = TensorDataset(inputs,targets) #merging inputs and targets
train_data[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [28]:
from torch.utils.data import DataLoader
batch_size=6
train_dl=DataLoader(train_data,batch_size,shuffle=True) #shuffling and batching

In [30]:
print(*train_dl)

[tensor([[ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 92.,  87.,  64.],
        [ 91.,  87.,  65.],
        [ 68.,  96.,  71.],
        [ 87., 135.,  57.]]), tensor([[119., 133.],
        [103., 119.],
        [ 82., 100.],
        [ 80., 102.],
        [104., 118.],
        [118., 134.]])] [tensor([[ 73.,  67.,  43.],
        [ 74.,  66.,  43.],
        [ 68.,  97.,  70.],
        [ 73.,  66.,  44.],
        [103.,  43.,  36.],
        [102.,  43.,  37.]]), tensor([[ 56.,  70.],
        [ 57.,  69.],
        [102., 120.],
        [ 57.,  69.],
        [ 20.,  38.],
        [ 22.,  37.]])] [tensor([[ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 91.,  88.,  64.]]), tensor([[118., 132.],
        [ 21.,  38.],
        [ 81., 101.]])]


In [31]:
#defining model
model=nn.Linear(3,2) #3 attributes and 2 classes
print(model.weight
      )
print(model.bias) # these weights and bias are randomly initialized

Parameter containing:
tensor([[-0.1227, -0.2129, -0.0994],
        [ 0.5752, -0.3603, -0.5487]], requires_grad=True)
Parameter containing:
tensor([0.1161, 0.4625], requires_grad=True)


In [36]:
print(*model.parameters())

Parameter containing:
tensor([[-0.1227, -0.2129, -0.0994],
        [ 0.5752, -0.3603, -0.5487]], requires_grad=True) Parameter containing:
tensor([0.1161, 0.4625], requires_grad=True)


In [38]:
preds=model(inputs)
preds

tensor([[-27.3832,  -5.2805],
        [-36.1509, -14.0155],
        [-44.8589, -29.5997],
        [-25.2355,  23.3415],
        [-35.7506, -32.8456],
        [-27.2930,  -4.3450],
        [-36.0373, -14.2039],
        [-45.0810, -29.5731],
        [-25.3257,  22.4059],
        [-35.7272, -33.9695],
        [-27.2696,  -5.4689],
        [-36.0607, -13.0800],
        [-44.9725, -29.4113],
        [-25.2589,  24.4654],
        [-35.8408, -33.7812]], grad_fn=<AddmmBackward>)

In [40]:
#defining loss function
from torch.nn.functional import mse_loss
loss_fn=mse_loss

In [41]:
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(13742.1836, grad_fn=<MseLossBackward>)


In [42]:
#defining optimizer
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [44]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [46]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 1162.7413
Epoch [20/100], Loss: 1515.1595
Epoch [30/100], Loss: 462.9326
Epoch [40/100], Loss: 618.8602
Epoch [50/100], Loss: 12.5430
Epoch [60/100], Loss: 196.4310
Epoch [70/100], Loss: 107.9281
Epoch [80/100], Loss: 132.6216
Epoch [90/100], Loss: 117.1911
Epoch [100/100], Loss: 52.6924


In [47]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.1304,  72.4559],
        [ 80.6146,  95.9402],
        [118.7710, 138.1354],
        [ 27.9319,  50.1120],
        [ 95.3203, 103.5120],
        [ 57.0262,  71.5537],
        [ 80.1671,  95.1471],
        [118.9445, 138.3194],
        [ 29.0361,  51.0142],
        [ 95.9769, 103.6210],
        [ 57.6828,  71.6628],
        [ 79.5105,  95.0380],
        [119.2185, 138.9286],
        [ 27.2752,  50.0030],
        [ 96.4244, 104.4142]], grad_fn=<AddmmBackward>)

In [48]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [49]:
#single sample
model(torch.tensor([[75, 63, 44.]]))

tensor([[54.6119, 68.9188]], grad_fn=<AddmmBackward>)