In [2]:
import torch
import numpy as np


In [3]:
#Train data
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
print(inputs.shape)

(5, 3)


In [4]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [5]:
#weights and biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
w,b

(tensor([[ 0.1973,  0.0023, -0.1046],
         [ 0.0676, -0.6210,  0.0832]], requires_grad=True),
 tensor([ 0.4570, -0.7914], requires_grad=True))

In [8]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [9]:
def model(input_values):
  return input_values@w.t() + b


In [14]:
pred=model(inputs)

In [15]:
#mse loss
def mse(predictions,targets):
  diff=predictions-targets
  return torch.sum(diff*diff)/diff.numel()


In [16]:
loss=mse(pred,targets)
print(loss)

tensor(13344.1904, grad_fn=<DivBackward0>)


In [17]:
loss.backward()

In [18]:
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[ 0.1973,  0.0023, -0.1046],
        [ 0.0676, -0.6210,  0.0832]], requires_grad=True)
tensor([[ -5216.3110,  -6584.6738,  -3900.8203],
        [-11188.2041, -13184.6270,  -7910.4961]])
tensor([ 0.4570, -0.7914], requires_grad=True)
tensor([ -64.5808, -135.7204])


In [19]:
with torch.no_grad():
  w -= w.grad*1e-5
  b -=b.grad*1e-5
  print(w)
  print(b)
  

tensor([[ 0.2495,  0.0682, -0.0656],
        [ 0.1795, -0.4892,  0.1623]], requires_grad=True)
tensor([ 0.4576, -0.7900], requires_grad=True)


In [22]:
mse(pred,targets)

tensor(13344.1904, grad_fn=<DivBackward0>)

In [24]:
w.grad.zero_()
b.grad.zero_()
w.grad,b.grad

(tensor([[0., 0., 0.],
         [0., 0., 0.]]), tensor([0., 0.]))

In [26]:
# sequential implementation 
pred=model(inputs)
print(pred)
loss=mse(pred,targets)
print(loss)


tensor([[ 20.4166, -13.4843],
        [ 24.9614, -17.1181],
        [ 27.4926, -41.3126],
        [ 26.4093,   2.4875],
        [ 19.6245, -24.0065]], grad_fn=<AddBackward0>)
tensor(9269.9404, grad_fn=<DivBackward0>)


In [27]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -4192.2803,  -5478.3848,  -3219.4248],
        [ -9079.2051, -10911.6797,  -6509.3867]])
tensor([ -52.4191, -110.6868])


In [28]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
    print(w)
    print(b)

tensor([[ 0.2914,  0.1229, -0.0334],
        [ 0.2703, -0.3801,  0.2274]], requires_grad=True)
tensor([ 0.4582, -0.7889], requires_grad=True)


In [29]:
print(w)
print(b)

tensor([[ 0.2914,  0.1229, -0.0334],
        [ 0.2703, -0.3801,  0.2274]], requires_grad=True)
tensor([ 0.4582, -0.7889], requires_grad=True)


In [30]:
# Calculate loss
preds = model(inputs) #to see a change in loss we need to go with new predictions for the model after the gradient updation
loss = mse(preds, targets)
print(loss)

tensor(6520.9233, grad_fn=<DivBackward0>)


In [36]:
for _ in range(100): #training for 100 epochs
    preds=model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
      w -= w.grad*1e-5
      b -= b.grad*1e-5
      w.grad.zero_()
      b.grad.zero_()
print(loss)


tensor(255.8309, grad_fn=<DivBackward0>)


In [37]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(252.7750, grad_fn=<DivBackward0>)
